# ansible-playbook playbooks/nginx.yml
- name: NGINX
  hosts: all
  tasks:
    - name: NGINX | Install
      tags: Install
      become: yes
      apt:
        name: nginx
        state: latest

    - name: NGINX | Start
      tags: Start
      shell:
        cmd: '/etc/init.d/nginx start'
      notify: NGINX | Hello Message

    # Docker does not have systemd
    #
    # - name: NGINX | Start
    #   service:
    #     name: nginx
    #     state: started

  handlers:
    - name: NGINX | Hello Message
      shell:
        cmd: 'ls -al .'
      register: output
      notify: NGINX | Debug

    - name: NGINX | Debug
      debug:
        msg: "{{ output.stdout_lines }}"
