# ansible-playbook playbooks/nginx.yml
- name: NGINX
  hosts: all
  tasks:
    - name: NGINX | Install
      tags: Install
      become: yes
      apt:
        name: nginx
        state: latest

    - name: NGINX | Start
      tags: Start
      shell:
        cmd: '/etc/init.d/nginx start'

    # Docker does not have systemd
    #
    # - name: NGINX | Start
    #   service:
    #     name: nginx
    #     state: started
